# Generated by Django 4.0.5 on 2022-06-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=123)),
                ('user', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
